name: "finapi"

services:
  php:
    build: ./docker
    image: finapi
    container_name: finapi-php
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor

  nginx:
    image: nginx:stable-alpine-slim
    container_name: finapi-proxy
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
